//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rsi.Entities.configurations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class slider {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal slider() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("rsi.Entities.configurations.slider", typeof(slider).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/content/advertisings/1.jpg.
        /// </summary>
        public static string slideImage1 {
            get {
                return ResourceManager.GetString("slideImage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/content/advertisings/10.jpg.
        /// </summary>
        public static string slideImage10 {
            get {
                return ResourceManager.GetString("slideImage10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/content/advertisings/2.jpg.
        /// </summary>
        public static string slideImage2 {
            get {
                return ResourceManager.GetString("slideImage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/content/advertisings/3.jpg.
        /// </summary>
        public static string slideImage3 {
            get {
                return ResourceManager.GetString("slideImage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/content/advertisings/4.jpg.
        /// </summary>
        public static string slideImage4 {
            get {
                return ResourceManager.GetString("slideImage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/content/advertisings/5.jpg.
        /// </summary>
        public static string slideImage5 {
            get {
                return ResourceManager.GetString("slideImage5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/content/advertisings/6.jpg.
        /// </summary>
        public static string slideImage6 {
            get {
                return ResourceManager.GetString("slideImage6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/content/advertisings/7.jpg.
        /// </summary>
        public static string slideImage7 {
            get {
                return ResourceManager.GetString("slideImage7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/content/advertisings/8.jpg.
        /// </summary>
        public static string slideImage8 {
            get {
                return ResourceManager.GetString("slideImage8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/content/advertisings/9.jpg.
        /// </summary>
        public static string slideImage9 {
            get {
                return ResourceManager.GetString("slideImage9", resourceCulture);
            }
        }
    }
}
