//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rsi.Entities.configurations {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class thePaths {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal thePaths() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("rsi.Entities.configurations.thePaths", typeof(thePaths).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ~/content/advertisers/.
        /// </summary>
        public static string advertisersImages {
            get {
                return ResourceManager.GetString("advertisersImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ~/content/advertisers/logos/.
        /// </summary>
        public static string AdvertisersLogo {
            get {
                return ResourceManager.GetString("AdvertisersLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ~/Views/_partialViews/Vitrines/_ad_sideBar.cshtml.
        /// </summary>
        public static string advertising_model_1_sideBar_unicModel {
            get {
                return ResourceManager.GetString("advertising_model_1_sideBar_unicModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ~/content/advertisings/.
        /// </summary>
        public static string advertisingsImages {
            get {
                return ResourceManager.GetString("advertisingsImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ~/content/categories/.
        /// </summary>
        public static string categoriesImages {
            get {
                return ResourceManager.GetString("categoriesImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ~/content/displays/.
        /// </summary>
        public static string displaysImages {
            get {
                return ResourceManager.GetString("displaysImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ~/assets/images/elements/.
        /// </summary>
        public static string elementsImages {
            get {
                return ResourceManager.GetString("elementsImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A:/_cloudDrives/Dropbox/developer/projects/rsi/rsi.Ui/.
        /// </summary>
        public static string fullPathRSI {
            get {
                return ResourceManager.GetString("fullPathRSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a http://dea0f0e8.iphotel.info/.
        /// </summary>
        public static string fullPathRSI_iPhotel {
            get {
                return ResourceManager.GetString("fullPathRSI_iPhotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ~/assets/images/icons/.
        /// </summary>
        public static string icons {
            get {
                return ResourceManager.GetString("icons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ~/assets/images/logos/.
        /// </summary>
        public static string logoImages {
            get {
                return ResourceManager.GetString("logoImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ~/content/menus/.
        /// </summary>
        public static string menuImages {
            get {
                return ResourceManager.GetString("menuImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ~/assets/images/elements/searchNotFoundImage.png.
        /// </summary>
        public static string searchNotFoundImagePath {
            get {
                return ResourceManager.GetString("searchNotFoundImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ~/Views/_partialViews/home/_contactMe.cshtml.
        /// </summary>
        public static string section_model_1_home_contact {
            get {
                return ResourceManager.GetString("section_model_1_home_contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ~/Views/_partialViews/home/_ourTeam.cshtml.
        /// </summary>
        public static string section_model_3_home_ourTeam {
            get {
                return ResourceManager.GetString("section_model_3_home_ourTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ~/Views/_partialViews/home/_ourNumbers.cshtml.
        /// </summary>
        public static string section_model_4_home_ourNumbers {
            get {
                return ResourceManager.GetString("section_model_4_home_ourNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ~/Views/_partialViews/home/_whoWeAre.cshtml.
        /// </summary>
        public static string section_model_5_home_ourNumbers {
            get {
                return ResourceManager.GetString("section_model_5_home_ourNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ~/Views/_partialViews/home/_aboutUs.cshtml.
        /// </summary>
        public static string section_model_6_home_aboutUs {
            get {
                return ResourceManager.GetString("section_model_6_home_aboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ~/Views/_partialViews/home/_welcome.cshtml.
        /// </summary>
        public static string section_model_7_home_welcome {
            get {
                return ResourceManager.GetString("section_model_7_home_welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ~/Views/_partialViews/home/_whyAdvertiseHere.cshtml.
        /// </summary>
        public static string section_model_8_home_whyAdvertiseHere {
            get {
                return ResourceManager.GetString("section_model_8_home_whyAdvertiseHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ~/Views/_partialViews/home/_youWantToAdvertiseHere.cshtml.
        /// </summary>
        public static string section_model_9_home_youWantToAdvertiseHe {
            get {
                return ResourceManager.GetString("section_model_9_home_youWantToAdvertiseHe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a localhost.
        /// </summary>
        public static string servidor {
            get {
                return ResourceManager.GetString("servidor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ~/Views/_partialViews/displays/_showCase_model_1_grid.cshtml.
        /// </summary>
        public static string showCase_model_1_grid {
            get {
                return ResourceManager.GetString("showCase_model_1_grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ~/Views/_partialViews/displays/_showCase_model_10_list_withFilter.cshtml.
        /// </summary>
        public static string showCase_model_10_list_withFilter {
            get {
                return ResourceManager.GetString("showCase_model_10_list_withFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ~/Views/_partialViews/displays/_showCase_model_11_slider.cshtml.
        /// </summary>
        public static string showCase_model_11_slider {
            get {
                return ResourceManager.GetString("showCase_model_11_slider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ~/Views/_partialViews/displays/_showCase_model_12_grid_oneLine.cshtml.
        /// </summary>
        public static string showCase_model_12_grid_oneLine {
            get {
                return ResourceManager.GetString("showCase_model_12_grid_oneLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ~/Views/_partialViews/displays/_showCase_model_13_brandsCarousel.cshtml.
        /// </summary>
        public static string showCase_model_13_brandsCarousel {
            get {
                return ResourceManager.GetString("showCase_model_13_brandsCarousel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ~/Views/_partialViews/displays/_showCase_model_2_grid_withFilter.cshtml.
        /// </summary>
        public static string showCase_model_2_grid_withFilter {
            get {
                return ResourceManager.GetString("showCase_model_2_grid_withFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ~/Views/_partialViews/displays/_showCase_model_3_gridCarousel.cshtml.
        /// </summary>
        public static string showCase_model_3_gridCarousel {
            get {
                return ResourceManager.GetString("showCase_model_3_gridCarousel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ~/Views/_partialViews/displays/_showCase_model_4_gridCarousel_withFilter.cshtml.
        /// </summary>
        public static string showCase_model_4_gridCarousel_withFilter {
            get {
                return ResourceManager.GetString("showCase_model_4_gridCarousel_withFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /ShowCases/CarouselOneLine.
        /// </summary>
        public static string showCase_model_5_carousel {
            get {
                return ResourceManager.GetString("showCase_model_5_carousel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ~/Views/_partialViews/displays/_showCase_model_6_carousel_withFilter.cshtml.
        /// </summary>
        public static string showCase_model_6_carousel_withFilter {
            get {
                return ResourceManager.GetString("showCase_model_6_carousel_withFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ~/Views/_partialViews/displays/_showCase_model_7_carousel2.cshtml.
        /// </summary>
        public static string showCase_model_7_carousel2 {
            get {
                return ResourceManager.GetString("showCase_model_7_carousel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ~/Views/_partialViews/displays/_showCase_model_8_metro.cshtml.
        /// </summary>
        public static string showCase_model_8_metro {
            get {
                return ResourceManager.GetString("showCase_model_8_metro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ~/Views/_partialViews/displays/_showCase_model_9_list.cshtml.
        /// </summary>
        public static string showCase_model_9_list {
            get {
                return ResourceManager.GetString("showCase_model_9_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ~/content/showcases/.
        /// </summary>
        public static string showCasesImages {
            get {
                return ResourceManager.GetString("showCasesImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a http://dea0f0e8.iphotel.info.
        /// </summary>
        public static string siteRSI_url {
            get {
                return ResourceManager.GetString("siteRSI_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ~/assets/images/elements/stripes/.
        /// </summary>
        public static string stripes {
            get {
                return ResourceManager.GetString("stripes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ~/content/subCategories/.
        /// </summary>
        public static string subCategoriesImages {
            get {
                return ResourceManager.GetString("subCategoriesImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ~/content/users/.
        /// </summary>
        public static string usersImages {
            get {
                return ResourceManager.GetString("usersImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ~/content/vitrines/.
        /// </summary>
        public static string vitrinesImages {
            get {
                return ResourceManager.GetString("vitrinesImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ~/Views/_partialViews/Vitrines/.
        /// </summary>
        public static string vitrinesViews {
            get {
                return ResourceManager.GetString("vitrinesViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ~/Views/_partialViews/home/_categoriesMenu.cshtml.
        /// </summary>
        public static string widget_model_1_home_categoriesMenu {
            get {
                return ResourceManager.GetString("widget_model_1_home_categoriesMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ~/Views/_partialViews/sideBar/_categoriesMenu.cshtml.
        /// </summary>
        public static string widget_model_2_sideBar_categoriesMenu {
            get {
                return ResourceManager.GetString("widget_model_2_sideBar_categoriesMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ~/Views/_partialViews/sideBar/_tagsCloud.cshtml.
        /// </summary>
        public static string widget_model_3_sideBar_tagsCloud {
            get {
                return ResourceManager.GetString("widget_model_3_sideBar_tagsCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ~/Views/_partialViews/sideBar/_googleAdWords_sidebar.cshtml.
        /// </summary>
        public static string widget_model_4_sideBar_google_AdWords {
            get {
                return ResourceManager.GetString("widget_model_4_sideBar_google_AdWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ~/Views/_partialViews/home/_googleAdWords.cshtml.
        /// </summary>
        public static string widget_model_5_home_google_AdWords {
            get {
                return ResourceManager.GetString("widget_model_5_home_google_AdWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ~/Views/_partialViews/home/_welcome.cshtml.
        /// </summary>
        public static string widget_model_7_home_welcome {
            get {
                return ResourceManager.GetString("widget_model_7_home_welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ~/Views/_partialViews/header/_mainMenu.cshtml.
        /// </summary>
        public static string widget_model_8_header_mainMenu {
            get {
                return ResourceManager.GetString("widget_model_8_header_mainMenu", resourceCulture);
            }
        }
    }
}
