//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rsi.Entities.configurations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class theSetup {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal theSetup() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("rsi.Entities.configurations.theSetup", typeof(theSetup).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _display_carousel_pictureAndSlogan.cshtml.
        /// </summary>
        public static string carousel_pictureAndSlogan {
            get {
                return ResourceManager.GetString("carousel_pictureAndSlogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _display_carousel_pictureAndSlogan_With_Filter.cshtml.
        /// </summary>
        public static string carousel_pictureAndSlogan_With_Filter {
            get {
                return ResourceManager.GetString("carousel_pictureAndSlogan_With_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to anselmo@softbox.com.br.
        /// </summary>
        public static string email_Cc {
            get {
                return ResourceManager.GetString("email_Cc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to anselmolucas@gmail.com.
        /// </summary>
        public static string email_client_Credentials {
            get {
                return ResourceManager.GetString("email_client_Credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shyv@1966.
        /// </summary>
        public static string email_client_Credentials_password {
            get {
                return ResourceManager.GetString("email_client_Credentials_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smtp.gmail.com.
        /// </summary>
        public static string email_client_Host {
            get {
                return ResourceManager.GetString("email_client_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to visitante do site RSI.
        /// </summary>
        public static string email_senderName {
            get {
                return ResourceManager.GetString("email_senderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to anselmo.lucas@hotmail.com.
        /// </summary>
        public static string email_To {
            get {
                return ResourceManager.GetString("email_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/assets/images/logos/favicon.png.
        /// </summary>
        public static string favicon {
            get {
                return ResourceManager.GetString("favicon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon_address.png.
        /// </summary>
        public static string iconAdress {
            get {
                return ResourceManager.GetString("iconAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon_alelo.png.
        /// </summary>
        public static string iconAlelo {
            get {
                return ResourceManager.GetString("iconAlelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon_noImage.png.
        /// </summary>
        public static string iconBlog {
            get {
                return ResourceManager.GetString("iconBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon_boleto.png.
        /// </summary>
        public static string iconBoleto {
            get {
                return ResourceManager.GetString("iconBoleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon_bradesco.png.
        /// </summary>
        public static string iconBradesco {
            get {
                return ResourceManager.GetString("iconBradesco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon_clock.png.
        /// </summary>
        public static string iconClock {
            get {
                return ResourceManager.GetString("iconClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon_email.png.
        /// </summary>
        public static string iconEmail {
            get {
                return ResourceManager.GetString("iconEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon_facebook.png.
        /// </summary>
        public static string iconFacebook {
            get {
                return ResourceManager.GetString("iconFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon_noImage.png.
        /// </summary>
        public static string iconFlickr {
            get {
                return ResourceManager.GetString("iconFlickr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon_gallery.png.
        /// </summary>
        public static string iconGallery {
            get {
                return ResourceManager.GetString("iconGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon_googlePlus.png.
        /// </summary>
        public static string iconGooglePlus {
            get {
                return ResourceManager.GetString("iconGooglePlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon_instagram.png.
        /// </summary>
        public static string iconInstagram {
            get {
                return ResourceManager.GetString("iconInstagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon_itau.png.
        /// </summary>
        public static string iconItau {
            get {
                return ResourceManager.GetString("iconItau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon_linkedin.png.
        /// </summary>
        public static string iconLinkedin {
            get {
                return ResourceManager.GetString("iconLinkedin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon_map.png.
        /// </summary>
        public static string iconMap {
            get {
                return ResourceManager.GetString("iconMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon_master.ico.
        /// </summary>
        public static string iconMaster {
            get {
                return ResourceManager.GetString("iconMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon_money.png.
        /// </summary>
        public static string iconMoney {
            get {
                return ResourceManager.GetString("iconMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon_noImage.png.
        /// </summary>
        public static string iconMySpace {
            get {
                return ResourceManager.GetString("iconMySpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon_pirate.jpg.
        /// </summary>
        public static string iconNoImage {
            get {
                return ResourceManager.GetString("iconNoImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon_pagseguro.gif.
        /// </summary>
        public static string iconPagSeguro {
            get {
                return ResourceManager.GetString("iconPagSeguro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon_paypal.png.
        /// </summary>
        public static string iconPaypal {
            get {
                return ResourceManager.GetString("iconPaypal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon_pdf.png.
        /// </summary>
        public static string iconPdf {
            get {
                return ResourceManager.GetString("iconPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon_picture.png.
        /// </summary>
        public static string iconPicture {
            get {
                return ResourceManager.GetString("iconPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon_noImage.png.
        /// </summary>
        public static string iconPinterest {
            get {
                return ResourceManager.GetString("iconPinterest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon_site.png.
        /// </summary>
        public static string iconSite {
            get {
                return ResourceManager.GetString("iconSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon_noImage.png.
        /// </summary>
        public static string iconSkype {
            get {
                return ResourceManager.GetString("iconSkype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon_soundCloud.ico.
        /// </summary>
        public static string iconSoundCloud {
            get {
                return ResourceManager.GetString("iconSoundCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon_tel.png.
        /// </summary>
        public static string iconTel {
            get {
                return ResourceManager.GetString("iconTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon_twitter.png.
        /// </summary>
        public static string iconTwitter {
            get {
                return ResourceManager.GetString("iconTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon_txt.png.
        /// </summary>
        public static string iconTxt {
            get {
                return ResourceManager.GetString("iconTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon_url.png.
        /// </summary>
        public static string iconUrl {
            get {
                return ResourceManager.GetString("iconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon_video.png.
        /// </summary>
        public static string iconVideo {
            get {
                return ResourceManager.GetString("iconVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon_vimeo.png.
        /// </summary>
        public static string iconVimeo {
            get {
                return ResourceManager.GetString("iconVimeo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon_visa.png.
        /// </summary>
        public static string iconVisa {
            get {
                return ResourceManager.GetString("iconVisa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon_whatsapp.png.
        /// </summary>
        public static string iconWhatsApp {
            get {
                return ResourceManager.GetString("iconWhatsApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon_youtube.png.
        /// </summary>
        public static string iconYoutube {
            get {
                return ResourceManager.GetString("iconYoutube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 165.
        /// </summary>
        public static string image_advertising_height {
            get {
                return ResourceManager.GetString("image_advertising_height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 250.
        /// </summary>
        public static string image_advertising_width {
            get {
                return ResourceManager.GetString("image_advertising_width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 155.
        /// </summary>
        public static string image_icon_height {
            get {
                return ResourceManager.GetString("image_icon_height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 155.
        /// </summary>
        public static string image_icon_width {
            get {
                return ResourceManager.GetString("image_icon_width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 350.
        /// </summary>
        public static string image_mainImage_height {
            get {
                return ResourceManager.GetString("image_mainImage_height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 450.
        /// </summary>
        public static string image_mainImage_width {
            get {
                return ResourceManager.GetString("image_mainImage_width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/assets/images/logos/logo.png.
        /// </summary>
        public static string logo {
            get {
                return ResourceManager.GetString("logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon_noImage.png.
        /// </summary>
        public static string noImage {
            get {
                return ResourceManager.GetString("noImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/assets/images/icons/icon_noImage.png.
        /// </summary>
        public static string noImage_path {
            get {
                return ResourceManager.GetString("noImage_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _adv.
        /// </summary>
        public static string prefixAdvertiserImag {
            get {
                return ResourceManager.GetString("prefixAdvertiserImag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _ad-.
        /// </summary>
        public static string prefixAdvertisingImag {
            get {
                return ResourceManager.GetString("prefixAdvertisingImag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _cat.
        /// </summary>
        public static string prefixCategoryImage {
            get {
                return ResourceManager.GetString("prefixCategoryImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _dsp.
        /// </summary>
        public static string prefixDisplayImage {
            get {
                return ResourceManager.GetString("prefixDisplayImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _mn-.
        /// </summary>
        public static string prefixDisplaysMenuDirectImage {
            get {
                return ResourceManager.GetString("prefixDisplaysMenuDirectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _sub.
        /// </summary>
        public static string prefixSubCategoryImage {
            get {
                return ResourceManager.GetString("prefixSubCategoryImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _use.
        /// </summary>
        public static string prefixUserImag {
            get {
                return ResourceManager.GetString("prefixUserImag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _vit.
        /// </summary>
        public static string prefixVitrineImag {
            get {
                return ResourceManager.GetString("prefixVitrineImag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encontre aqui tudo o que você procura....
        /// </summary>
        public static string searchbar_text {
            get {
                return ResourceManager.GetString("searchbar_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSI - Rosana Scott Indica.
        /// </summary>
        public static string siteDescription {
            get {
                return ResourceManager.GetString("siteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As melhores opções de compras e serviços.
        /// </summary>
        public static string slogan {
            get {
                return ResourceManager.GetString("slogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stripe_right_hot2.png.
        /// </summary>
        public static string stripe1_right {
            get {
                return ResourceManager.GetString("stripe1_right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stripe_right_sale.png.
        /// </summary>
        public static string stripe2_right {
            get {
                return ResourceManager.GetString("stripe2_right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/_partialViews/Vitrines/_ad_sideBar.cshtml.
        /// </summary>
        public static string view_ad_sidebar {
            get {
                return ResourceManager.GetString("view_ad_sidebar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _display_carouselOneLine.cshtml.
        /// </summary>
        public static string vitrineView_carouselOneLine {
            get {
                return ResourceManager.GetString("vitrineView_carouselOneLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _display_carouselOneLine_withFilter.cshtml.
        /// </summary>
        public static string vitrineView_carouselOneLine_withFilter {
            get {
                return ResourceManager.GetString("vitrineView_carouselOneLine_withFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _display_grid.cshtml.
        /// </summary>
        public static string vitrineView_grid {
            get {
                return ResourceManager.GetString("vitrineView_grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _display_grid_withFilter.cshtml.
        /// </summary>
        public static string vitrineView_grid_withFilter {
            get {
                return ResourceManager.GetString("vitrineView_grid_withFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c:/Users/ansel/xml/config.xml.
        /// </summary>
        public static string xmlPath {
            get {
                return ResourceManager.GetString("xmlPath", resourceCulture);
            }
        }
    }
}
