//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rsi.Entities.configurations {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class theSetup {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal theSetup() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("rsi.Entities.configurations.theSetup", typeof(theSetup).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a _display_carousel_pictureAndSlogan.cshtml.
        /// </summary>
        public static string carousel_pictureAndSlogan {
            get {
                return ResourceManager.GetString("carousel_pictureAndSlogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a _display_carousel_pictureAndSlogan_With_Filter.cshtml.
        /// </summary>
        public static string carousel_pictureAndSlogan_With_Filter {
            get {
                return ResourceManager.GetString("carousel_pictureAndSlogan_With_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a anselmo@softbox.com.br.
        /// </summary>
        public static string email_Cc {
            get {
                return ResourceManager.GetString("email_Cc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a anselmolucas@gmail.com.
        /// </summary>
        public static string email_client_Credentials {
            get {
                return ResourceManager.GetString("email_client_Credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Shyv@1966.
        /// </summary>
        public static string email_client_Credentials_password {
            get {
                return ResourceManager.GetString("email_client_Credentials_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a smtp.gmail.com.
        /// </summary>
        public static string email_client_Host {
            get {
                return ResourceManager.GetString("email_client_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a visitante do site RSI.
        /// </summary>
        public static string email_senderName {
            get {
                return ResourceManager.GetString("email_senderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a anselmo.lucas@hotmail.com.
        /// </summary>
        public static string email_To {
            get {
                return ResourceManager.GetString("email_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ~/assets/images/logos/favicon.png.
        /// </summary>
        public static string favicon {
            get {
                return ResourceManager.GetString("favicon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a icon_address.png.
        /// </summary>
        public static string iconAdress {
            get {
                return ResourceManager.GetString("iconAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a icon_alelo.png.
        /// </summary>
        public static string iconAlelo {
            get {
                return ResourceManager.GetString("iconAlelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a icon_noImage.png.
        /// </summary>
        public static string iconBlog {
            get {
                return ResourceManager.GetString("iconBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a icon_boleto.png.
        /// </summary>
        public static string iconBoleto {
            get {
                return ResourceManager.GetString("iconBoleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a icon_bradesco.png.
        /// </summary>
        public static string iconBradesco {
            get {
                return ResourceManager.GetString("iconBradesco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a icon_clock.png.
        /// </summary>
        public static string iconClock {
            get {
                return ResourceManager.GetString("iconClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a icon_email.png.
        /// </summary>
        public static string iconEmail {
            get {
                return ResourceManager.GetString("iconEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a icon_facebook.png.
        /// </summary>
        public static string iconFacebook {
            get {
                return ResourceManager.GetString("iconFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a icon_noImage.png.
        /// </summary>
        public static string iconFlickr {
            get {
                return ResourceManager.GetString("iconFlickr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a icon_gallery.png.
        /// </summary>
        public static string iconGallery {
            get {
                return ResourceManager.GetString("iconGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a icon_googlePlus.png.
        /// </summary>
        public static string iconGooglePlus {
            get {
                return ResourceManager.GetString("iconGooglePlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a icon_instagram.png.
        /// </summary>
        public static string iconInstagram {
            get {
                return ResourceManager.GetString("iconInstagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a icon_itau.png.
        /// </summary>
        public static string iconItau {
            get {
                return ResourceManager.GetString("iconItau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a icon_linkedin.png.
        /// </summary>
        public static string iconLinkedin {
            get {
                return ResourceManager.GetString("iconLinkedin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a icon_map.png.
        /// </summary>
        public static string iconMap {
            get {
                return ResourceManager.GetString("iconMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a icon_master.ico.
        /// </summary>
        public static string iconMaster {
            get {
                return ResourceManager.GetString("iconMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a icon_money.png.
        /// </summary>
        public static string iconMoney {
            get {
                return ResourceManager.GetString("iconMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a icon_noImage.png.
        /// </summary>
        public static string iconMySpace {
            get {
                return ResourceManager.GetString("iconMySpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a icon_pirate.jpg.
        /// </summary>
        public static string iconNoImage {
            get {
                return ResourceManager.GetString("iconNoImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a icon_pagseguro.gif.
        /// </summary>
        public static string iconPagSeguro {
            get {
                return ResourceManager.GetString("iconPagSeguro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a icon_paypal.png.
        /// </summary>
        public static string iconPaypal {
            get {
                return ResourceManager.GetString("iconPaypal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a icon_pdf.png.
        /// </summary>
        public static string iconPdf {
            get {
                return ResourceManager.GetString("iconPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a icon_picture.png.
        /// </summary>
        public static string iconPicture {
            get {
                return ResourceManager.GetString("iconPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a icon_noImage.png.
        /// </summary>
        public static string iconPinterest {
            get {
                return ResourceManager.GetString("iconPinterest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a icon_site.png.
        /// </summary>
        public static string iconSite {
            get {
                return ResourceManager.GetString("iconSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a icon_noImage.png.
        /// </summary>
        public static string iconSkype {
            get {
                return ResourceManager.GetString("iconSkype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a icon_soundCloud.ico.
        /// </summary>
        public static string iconSoundCloud {
            get {
                return ResourceManager.GetString("iconSoundCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a icon_tel.png.
        /// </summary>
        public static string iconTel {
            get {
                return ResourceManager.GetString("iconTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a icon_twitter.png.
        /// </summary>
        public static string iconTwitter {
            get {
                return ResourceManager.GetString("iconTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a icon_txt.png.
        /// </summary>
        public static string iconTxt {
            get {
                return ResourceManager.GetString("iconTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a icon_url.png.
        /// </summary>
        public static string iconUrl {
            get {
                return ResourceManager.GetString("iconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a icon_video.png.
        /// </summary>
        public static string iconVideo {
            get {
                return ResourceManager.GetString("iconVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a icon_vimeo.png.
        /// </summary>
        public static string iconVimeo {
            get {
                return ResourceManager.GetString("iconVimeo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a icon_visa.png.
        /// </summary>
        public static string iconVisa {
            get {
                return ResourceManager.GetString("iconVisa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a icon_whatsapp.png.
        /// </summary>
        public static string iconWhatsApp {
            get {
                return ResourceManager.GetString("iconWhatsApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a icon_youtube.png.
        /// </summary>
        public static string iconYoutube {
            get {
                return ResourceManager.GetString("iconYoutube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 165.
        /// </summary>
        public static string image_advertising_height {
            get {
                return ResourceManager.GetString("image_advertising_height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 250.
        /// </summary>
        public static string image_advertising_width {
            get {
                return ResourceManager.GetString("image_advertising_width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 155.
        /// </summary>
        public static string image_icon_height {
            get {
                return ResourceManager.GetString("image_icon_height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 155.
        /// </summary>
        public static string image_icon_width {
            get {
                return ResourceManager.GetString("image_icon_width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 350.
        /// </summary>
        public static string image_mainImage_height {
            get {
                return ResourceManager.GetString("image_mainImage_height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 450.
        /// </summary>
        public static string image_mainImage_width {
            get {
                return ResourceManager.GetString("image_mainImage_width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ~/assets/images/logos/logo.png.
        /// </summary>
        public static string logo {
            get {
                return ResourceManager.GetString("logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a icon_noImage.png.
        /// </summary>
        public static string noImage {
            get {
                return ResourceManager.GetString("noImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ~/assets/images/icons/icon_noImage.png.
        /// </summary>
        public static string noImage_path {
            get {
                return ResourceManager.GetString("noImage_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a _adv.
        /// </summary>
        public static string prefixAdvertiserImag {
            get {
                return ResourceManager.GetString("prefixAdvertiserImag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a _ad-.
        /// </summary>
        public static string prefixAdvertisingImag {
            get {
                return ResourceManager.GetString("prefixAdvertisingImag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a _cat.
        /// </summary>
        public static string prefixCategoryImage {
            get {
                return ResourceManager.GetString("prefixCategoryImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a _dsp.
        /// </summary>
        public static string prefixDisplayImage {
            get {
                return ResourceManager.GetString("prefixDisplayImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a _mn-.
        /// </summary>
        public static string prefixDisplaysMenuDirectImage {
            get {
                return ResourceManager.GetString("prefixDisplaysMenuDirectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a _sub.
        /// </summary>
        public static string prefixSubCategoryImage {
            get {
                return ResourceManager.GetString("prefixSubCategoryImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a _use.
        /// </summary>
        public static string prefixUserImag {
            get {
                return ResourceManager.GetString("prefixUserImag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a _vit.
        /// </summary>
        public static string prefixVitrineImag {
            get {
                return ResourceManager.GetString("prefixVitrineImag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Encontre aqui tudo o que você procura....
        /// </summary>
        public static string searchbar_text {
            get {
                return ResourceManager.GetString("searchbar_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a RSI - Rosana Scott Indica.
        /// </summary>
        public static string siteDescription {
            get {
                return ResourceManager.GetString("siteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a As melhores opções de compras e serviços.
        /// </summary>
        public static string slogan {
            get {
                return ResourceManager.GetString("slogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a stripe_right_hot2.png.
        /// </summary>
        public static string stripe1_right {
            get {
                return ResourceManager.GetString("stripe1_right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a stripe_right_sale.png.
        /// </summary>
        public static string stripe2_right {
            get {
                return ResourceManager.GetString("stripe2_right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ~/Views/_partialViews/Vitrines/_ad_sideBar.cshtml.
        /// </summary>
        public static string view_ad_sidebar {
            get {
                return ResourceManager.GetString("view_ad_sidebar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a _display_carouselOneLine.cshtml.
        /// </summary>
        public static string vitrineView_carouselOneLine {
            get {
                return ResourceManager.GetString("vitrineView_carouselOneLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a _display_carouselOneLine_withFilter.cshtml.
        /// </summary>
        public static string vitrineView_carouselOneLine_withFilter {
            get {
                return ResourceManager.GetString("vitrineView_carouselOneLine_withFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a _display_grid.cshtml.
        /// </summary>
        public static string vitrineView_grid {
            get {
                return ResourceManager.GetString("vitrineView_grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a _display_grid_withFilter.cshtml.
        /// </summary>
        public static string vitrineView_grid_withFilter {
            get {
                return ResourceManager.GetString("vitrineView_grid_withFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a c:/Users/ansel/xml/config.xml.
        /// </summary>
        public static string xmlPath {
            get {
                return ResourceManager.GetString("xmlPath", resourceCulture);
            }
        }
    }
}
